OpenTTD/bananas-api

.github/workflows/deployment.yml
.github/workflows/publish.yml

Also, the name would have been wrong. Too much copy pasting from
another repo can hurt a bit.

Fix: [Actions] deployment was not triggered for staging

---

bananas_api/helpers/user_session.py

This causes the Python exception "dictionary changed size during
iteration".
Solve this by first making a new list out of it, before iterating.

Fix: cleaning up usersessions could modify the list while iterating

---

README.md
bananas_api/new_upload/session.py
bananas_api/web_routes/new.py
regression_runner/__main__.py

When using web-frontends around this API, two problems had to be
solved when uploading to tus:
1) tus needed the api-token, but the web-frontend normally doesn't
show this (as it is between the web-frontend server and the API;
the client has nothing to do with this). So switching to upload-token
only solves this problem. This is also security-wise safe, as the
upload-token is a secret generated on-demand. And it only lives for
roughly 15 minutes.
2) CORS is implemented, correctly, rather strict in tusd. This means
that we cannot use additional headers outside the ones in the CORS
header. This means that the upload-token has to move from headers
to Metadata. This also means that we have to trust the information
on disk about the upload. This too is security-wise safe, as this
file-uuid is …

Add: tus-endpoint now only needs upload-token and moved to Metadata

---

Dockerfile
README.md
bananas_api/__main__.py
bananas_api/helpers/api_schema.py
bananas_api/helpers/user_session.py
bananas_api/helpers/web_routes.py
bananas_api/user/base.py
bananas_api/user/developer.py
bananas_api/user/github.py
bananas_api/user/openttd.py
bananas_api/web_routes/user.py
clients-development.yaml
clients-production.yaml
clients-staging.yaml
regression_runner/__main__.py
regression_runner/clients.yaml
wishlist.txt

This avoids other websites being able to steal API tokens and
modify any content on the API, without the user knowing.

Fix: change the login flow to an OAuth2 PKCE flow

---

bananas_api/__main__.py
wishlist.txt

This means we listen to X-Forwarded-Proto when creating Location
headers in 301/302. This should solve CSP issues with tus file
uploading on production.

Add: allow indicate that we are behind a proxy

---

bananas_api/web_routes/new.py

Also, while at it, make sure we forget the reference before we
remove the file. In case this happens again, the impact would be
a lot smaller.

Fix: there is no .info file for extracted files

---

bananas_api/new_upload/exceptions.py
bananas_api/new_upload/extract.py
bananas_api/new_upload/session.py
bananas_api/new_upload/validate.py
regression/901_empty_tarball.yaml
regression/902_empty_zipfile.yaml

There currently isn't really a way to talk back to the client that
they uploaded an invalid tarball/zipfile. So far this only happened
when someone uploaded a zero-byte tarball, which is pretty obvious.
Hopefully that remains this way.
The behaviour is now: if you upload an invalid tarball/zipfile,
after pressing validate, the file is no longer in the filelist.
Hopefully that gives enough clues to the user what is going on.

Fix #65: ignore errors in tarballs/zipfiles

---

bananas_api/helpers/enums.py
bananas_api/web_routes/config.py
regression/000_success_newgrf.yaml
regression/950_condition_invalid.yaml
regression/951_condition_wrong_order.yaml
regression/952_condition_twice.yaml

```
It points to for example official vs patch-packs, to allow
future-extensions have uploads that are restricted to patch-packs.
```
This commit allows us to deploy this, and rename the entries in the storage. After that is done, we can remove the old entry.
While we are doing this, temporary the frontend will show two compatibility lines. This might seem a bit off, but the window this is happening in should be rather short.

Change: rename "master" to "official", as it is not referencing a branch

---

regression_runner/__main__.py

This triggered a warning from aiohttp that the session was not
terminated cleanly.

Fix: regression-runner didn't clean up on exit

---

bananas_api/new_upload/readers/scenario.py

This causes OOM events on our infrastructure.
It happens because we read the whole chunk at once in memory, while
we actually don't care about the content. So instead, read it in
smaller chunks, reducing the memory footprint.

Fix: 4kx4k scenarios consume a high amount of RAM while validating

---

bananas_api/helpers/api_schema.py
regression/002_success_new_version.yaml
regression/953_condition_invalid_version.yaml
regression/954_condition_invalid_version_second.yaml

They should always be stable releases, so no postfixes of any kind.

Fix: versions in conditions are not validated

---

bananas_api/new_upload/readers/newgrf.py

This collects NewGRF features in the "feature" dict:
* Vehicles, industries, ... are counted via their IDs, independent of how many actions they use.
* 32bpp, zoom-in, ... are treated as features, with spriteids as IDs, so you can compute percentages of sprites with 32bpp and sprites with zoom-in versions.
* ActionA and Action5 sprites are categorized into several BASETSET_xxx categories.

Add: more detailed analysis of NewGRF content.

---

bananas_api/helpers/api_schema.py
bananas_api/helpers/enums.py
bananas_api/new_upload/classifiers/newgrf.py

It makes more sense, to have it as a toggle. High/standard doesn't sound good.

Fix: rename NewGRF classifier "resolution" to "has-high-res"

---

bananas_api/helpers/api_schema.py
bananas_api/helpers/enums.py
bananas_api/new_upload/classifiers/heightmap.py
bananas_api/new_upload/readers/heightmap.py
bananas_api/new_upload/validate.py
bananas_api/tool_reclassify/__main__.py
bananas_api/tool_reclassify/heightmap.py
bananas_api/tool_reclassify/reclassify.py

This PR will make uploading heightmaps a lot slower .. some can take up to 20s to analyze. This is nothing new for BaNaNaS, as some NewGRFs take almost a minute. So in that sense .. this brings heightmaps on-par with NewGRFs.
Current classification:
https://gist.github.com/TrueBrain/57ebe63f17ef3dfcefabafa2af29cfe5
There is a `debug=` tag in there, which shows the height histogram of the heightmap, on which the `terrain-type` is based. It seems to show a good balance. It gives an indication to the user what to expect when you would create a game with this (assuming you use a sane Highest Peak setting, ofc).

Add: classify heightmaps with the information we can extract from it

---

Dockerfile
README.md
bananas_api/helpers/api_schema.py
bananas_api/helpers/regions.py
bananas_api/new_upload/session.py
bananas_api/new_upload/session_publish.py
bananas_api/new_upload/session_validation.py
bananas_api/tool_reclassify/reclassify.py
bananas_api/web_routes/config.py
region-iso-3166-1.json
region-iso-3166-2.json
region-un-m49.csv
regression/000_success_newgrf.yaml
regression/002_success_new_version.yaml
regression/100_success_base_sounds.yaml
regression/800_discover_self.yaml
regression/801_discover_content_type.yaml
regression/801_discover_unique_id.yaml
regression/960_invalid_region.yaml
regression/961_too_many_regions.yaml
regression_runner/__main__.py

We make use of two Open Source lists: UN M49 and ISO 3166-2. These two together give ~5400 regions to indicate what your content is about.

Feature: tag what region a NewGRF / Heightmap / Scenario is about

---

bananas_api/__main__.py
bananas_api/helpers/user_session.py

This fixes the warning that there is no event-loop yet (but it is created for you nevertheless).

Change: create a new event-loop on startup, instead of assuming it exists

---

bananas_api/user/github.py

As GitHub is IPv4-only, sometimes there is a need to proxy GitHub via other domains to enable IPv6 connectivity. For those cases, these settings are useful.

Add: allow defining the URL to use for GitHub for user authentication

---

bananas_api/storage/s3.py

This is needed to access S3-compatible buckets, like on Cloudflare R2.

Add: allow defining what S3 endpoint URL to use

---

.github/workflows/testing.yml
.gitignore
Dockerfile
bananas_api/new_upload/readers/heightmap.py
regression/311_invalid_heightmap.yaml
requirements.base
requirements.txt
setup.py
src/_bananas_api.cpp
src/_bananas_api.h
src/_heightmap.cpp

This fixes various of problems:
- The analysis itself consumes nearly no memory (where before it extracted the PNG in memory in full).
- The analysis is significantly faster (1000x faster).
- It uses the exact same code as OpenTTD, so no accidental conversion mistakes.
This means we can finally analyze heightmaps up to 256M tiles with ease.
Closes #373 (no longer applicable, as we no longer use Pillow)

Change: use a C-module to analyze heightmap

---

bananas_api/index/common_disk.py
bananas_api/tool_reclassify/reclassify.py
bananas_api/web_routes/user.py
regression_runner/__main__.py

The C-powered loader is about 6 times faster, and makes the startup go from ~30s to ~5s.

Change: speed-up startup by using C-powered YAML loader

---

bananas_api/new_upload/readers/scenario.py

This information was never used, and with 14.0 it changed sufficiently that it is also broken.

Remove: no longer analyze AI/GS for scenarios

---

bananas_api/new_upload/readers/scenario.py

Before TABLE chunks, SlArray (fixed-size arrays) weren't prefixed with a length indicator. But with the migration to TABLE chunks, they are. This is because otherwise there is no information in the savegame about the length of these fields, and would still require knowledge of the OpenTTD versions that created these chunks.
But, vanilla documented poorly that this was a change made, and with JGR's efforts in JGRPP to switch to TABLE chunks, this was overlooked. Now this doesn't show up when saving/loading games in-game, as everything is compatible. Although trying to load a JGRPP's savegame in Vanilla will also cause trouble.
Either way, BaNaNaS should just be able to load scenarios, no matter what OpenTTD produced them. As such, this proposed change.
It first detects a chunk that is …

Fix: JGRPP's NGRF chunk doesn't contain length indicators for fixed-size arrays

---

Dockerfile

Nowedays there is a linter complaining that if you do FROM you should do AS, not "as"

Fix: warning in Dockerfile
